name: CI

on: [push, pull_request]

jobs:
  build:
    name: CI workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker Images
        run: |
          docker --version

      - name: Slack Notify
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_CHANNEL: dev
          SLACK_MESSAGE: 'Upload & Run pipeline - ${{job.status}}'
          SLACK_USERNAME: Github Alert
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}